const webdriver = require('selenium-webdriver');
const by = webdriver.By;
const until = webdriver.until;
const driver = new webdriver.Builder().forBrowser('chrome').build();
const assert = require('assert');
const timeout = 3000;
const path = require('path');
const helpers = require(path.join(__dirname, '..', 'helpers.js'));

driver.manage().window().setSize(1280, 720);

const test = async() => {
    try {
        await driver.get('http://127.0.0.1:3000/admin/users');
        let title = await driver.getTitle();
        assert.ok(~title.indexOf('Log in'), 'Wrong title!');
        let fieldAuthUsername = await driver.findElement(by.id('zoiaAuth_username'));
        await fieldAuthUsername.sendKeys('admin');
        let fieldAuthPassword = await driver.findElement(by.id('zoiaAuth_password'));
        await fieldAuthPassword.sendKeys('admin');
        let fieldAuthCaptcha = await driver.findElement(by.id('zoiaAuth_captcha'));
        await fieldAuthCaptcha.sendKeys('1111');
        let btnAuthSave = await driver.findElement(by.id('zoiaAuth_btnSave'));
        await helpers.click(btnAuthSave, driver);
        await driver.wait(until.elementLocated(by.id('wrapTable')), timeout);
        let btnZoiaAdd = await driver.findElement(by.className('zoiaAddD'));
        await helpers.click(btnZoiaAdd, driver);
        await driver.wait(until.elementLocated(by.id('editDialogHeader')), timeout);
        await driver.wait(until.elementLocated(by.id('editForm_username')), timeout);
        let fieldEditUsername = await driver.findElement(by.id('editForm_username'));
        await fieldEditUsername.sendKeys('test1');
        let fieldEditEmail = await driver.findElement(by.id('editForm_email'));
        await fieldEditEmail.sendKeys('test1@domain.org');
        let fieldEditPassword = await driver.findElement(by.id('editForm_password'));
        await fieldEditPassword.sendKeys('12345');
        let fieldEditPasswordConfirm = await driver.findElement(by.id('editForm_passwordConfirm'));
        await fieldEditPasswordConfirm.sendKeys('12345');
        let fieldEditStatus = await driver.findElement(by.id('editForm_status'));
        await fieldEditStatus.sendKeys('Disabled');
        let btnEditSave = await driver.findElement(by.id('editForm_btnSave'));
        await helpers.click(btnEditSave, driver);
        await driver.wait(until.elementLocated(by.xpath('//*[@id="users"]/tbody/tr[2]/td[2]')), timeout);
        let usersTableCell22 = await driver.findElement(by.xpath('//*[@id="users"]/tbody/tr[2]/td[2]'));
        let addedUsername = await usersTableCell22.getText();
        assert.equal(addedUsername, 'test1', 'User not added');
        let usersTableCell23 = await driver.findElement(by.xpath('//*[@id="users"]/tbody/tr[2]/td[3]'));
        let addedEmail = await usersTableCell23.getText();
        assert.equal(addedEmail, 'test1@domain.org', 'E-mail not added');
        let usersTableCell24 = await driver.findElement(by.xpath('//*[@id="users"]/tbody/tr[2]/td[4]'));
        let addedStatus = await usersTableCell24.getText();
        assert.equal(addedStatus, 'Disabled', 'Status not added');
        let btnZoiaEdit = await driver.findElement(by.xpath('//*[@id="users"]/tbody/tr[2]/td[5]/button[1]'));
        await helpers.click(btnZoiaAdd, driver);
        await driver.wait(until.elementLocated(by.id('editForm_username')), timeout);
        await helpers.click(btnEditSave, driver);
        await helpers.waitForItem(by.id('editForm_username_error_text'), driver);
        let btnEditCancel = await driver.findElement(by.id('editForm_btnCancel'));
        await helpers.click(btnEditCancel, driver);
        await driver.wait(until.elementLocated(by.id('wrapTable')), timeout);
        await helpers.click(btnZoiaEdit, driver);
        await driver.wait(until.elementLocated(by.id('editForm_username')), timeout);
        await fieldEditUsername.clear();
        await fieldEditUsername.sendKeys('test2');
        await fieldEditEmail.clear();
        await fieldEditEmail.sendKeys('test2@domain.org');
        await fieldEditPassword.clear();
        await fieldEditPassword.sendKeys('45678');
        await fieldEditPasswordConfirm.clear();
        await fieldEditPasswordConfirm.sendKeys('45678');
        await fieldEditStatus.sendKeys('Administrator');
        await helpers.click(btnEditSave, driver);
        await helpers.waitForValue(by.xpath('//*[@id="users"]/tbody/tr[2]/td[2]'), 'test2', driver);
        usersTableCell22 = await driver.findElement(by.xpath('//*[@id="users"]/tbody/tr[2]/td[2]'));
        addedUsername = await usersTableCell22.getText();
        assert.equal(addedUsername, 'test2', 'Username not changed');
        usersTableCell23 = await driver.findElement(by.xpath('//*[@id="users"]/tbody/tr[2]/td[3]'));
        addedEmail = await usersTableCell23.getText();
        assert.equal(addedEmail, 'test2@domain.org', 'E-mail not changed');
        usersTableCell24 = await driver.findElement(by.xpath('//*[@id="users"]/tbody/tr[2]/td[4]'));
        addedStatus = await usersTableCell24.getText();
        assert.equal(addedStatus, 'Administrator', 'Status not changed');
        let btnZoiaDelete = await driver.findElement(by.xpath('//*[@id="users"]/tbody/tr[2]/td[5]/button[2]'));
        await helpers.click(btnZoiaDelete, driver);
        await driver.wait(until.elementLocated(by.id('zoiaDeleteDialogButton'), timeout));
        let zoiaDeleteDialogButton = await driver.findElement(by.id('zoiaDeleteDialogButton'));
        await helpers.click(zoiaDeleteDialogButton, driver);
        await driver.wait(until.elementLocated(by.id('editForm_username')), timeout);
        helpers.waitForDisappear(by.xpath('//*[@id="users"]/tbody/tr[2]/td[2]'), driver);
        driver.close();
        console.log('OK');
    } catch (e) {
        driver.close();
        console.log('Error: ' + e);
    }
};

test();